name: Custom Mod Log
options:
  bundleIdPrefix: com.shimondeitel.modlog
  deploymentTarget:
    iOS: "17.0"
  createIntermediateGroups: true
  groupSortPosition: top
settings:
  base:
    MARKETING_VERSION: "1.0"
    CURRENT_PROJECT_VERSION: "1"
    SWIFT_VERSION: "5.0"
    DEVELOPMENT_TEAM: "W7Q885Q59C"
    CODE_SIGN_STYLE: Automatic
    IPHONEOS_DEPLOYMENT_TARGET: "17.0"
    TARGETED_DEVICE_FAMILY: "1"
    ENABLE_USER_SCRIPT_SANDBOXING: "YES"
targets:
  Custom Mod Log:
    type: application
    platform: iOS
    sources:
      - path: Custom Mod Log
    settings:
      base:
        PRODUCT_BUNDLE_IDENTIFIER: com.shimondeitel.modlog
        TARGETED_DEVICE_FAMILY: "1"
        INFOPLIST_FILE: Custom Mod Log/Info.plist
        ASSETCATALOG_COMPILER_APPICON_NAME: AppIcon
        ASSETCATALOG_COMPILER_GLOBAL_ACCENT_COLOR_NAME: AccentColor
        ENABLE_PREVIEWS: "YES"
        GENERATE_INFOPLIST_FILE: "NO"
  Custom Mod LogTests:
    type: bundle.unit-test
    platform: iOS
    sources:
      - path: Custom Mod LogTests
      - path: Custom Mod Log.storekit
    dependencies:
      - target: Custom Mod Log
    settings:
      base:
        PRODUCT_BUNDLE_IDENTIFIER: com.shimondeitel.modlog.tests
        GENERATE_INFOPLIST_FILE: "YES"
        TARGETED_DEVICE_FAMILY: "1"
  Custom Mod LogUITests:
    type: bundle.ui-testing
    platform: iOS
    sources:
      - path: Custom Mod LogUITests
    dependencies:
      - target: Custom Mod Log
    settings:
      base:
        PRODUCT_BUNDLE_IDENTIFIER: com.shimondeitel.modlog.uitests
        GENERATE_INFOPLIST_FILE: "YES"
        TARGETED_DEVICE_FAMILY: "1"
schemes:
  Custom Mod Log:
    build:
      targets:
        Custom Mod Log: all
        Custom Mod LogTests: [test]
        Custom Mod LogUITests: [test]
    run:
      config: Debug
      storeKitConfiguration: Custom Mod Log.storekit
    test:
      config: Debug
      storeKitConfiguration: Custom Mod Log.storekit
      targets:
        - Custom Mod LogTests
        - Custom Mod LogUITests
    archive:
      config: Release
